### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by cryptohappyguy** [cryptopool-builders/multipool_setup#1]
Hi I am installing yiimp_single, first of all, thank you for your work it makes things easier.

1)
I am having following issue,for now installing in docker and came over some small issues it is really annoying as it keeps asking me the questions over and over again even though I have already list

$STORAGE_ROOT/yiimp/.yiimp.conf

could you make it so that when values are already in some file somewhere like enough to copy paste these values on to server and when they are filled out it wont ask you for those questions but only will confirm those values ?
2)
It would be great if it would work with any yiimp fork, whats required for that ?

**Comment by cryptohappyguy** [comment]
Also is pollinate really so important, it fails in docker so I removed it

**Comment by cryptopool-builders** [comment]
This was not written for Docker. I dont have any plans on supporting docker at this time.
